### ISSUE TITLE
Banner/Banner-Content Padding

### ISSUE THREAD

**Issue by bsherms** [bsherms/leafy-decorations#1]
@thomasjbradley
I'm having a hard time determining the padding for the banner and/or banner-content with a background image.
- I divided the image dimensions (2500 x 1664) to get the percentage for padding which is 66.56% but it's too large.

https://github.com/bsherms/leafy-decorations/blob/gh-pages/css/main.css#L44-L59

Thank you in advance! :)

**Comment by thomasjbradley** [comment]
I love that you’re doing the aspect ratio stuff! But, in this case, I have the padding top set to just `300px`.

**Comment by bsherms** [comment]
Awesome, thank you!
